version: '3.8'

services:
  service_c:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_c
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
